# Basic
title: He Art
subtitle: 个人技术博客
welcome_message: 记录开发过程中遇到的问题，欢迎了解更多。
description:  嗨，我是一名开发者。
creator: He Art

url: "https://HpArt.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

tag_button:
    title: 标签
    description: 技术文章分类
    url: 'https://HpArt.github.io/tag/'  

# Navigation buttons in the front page.
nav:
    #- {title: 简历, description: 我的简历, url: 'https://github.com/HpArt'}
    - {title: Git, description: 个人代码, url: 'https://github.com/HpArt'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 
    # duoshuo: 
    
# Social
social:
    github: HpArt
    mail: HpArt.arct@gmail.com

# Google Analytics
ga:
     id: UA-142143336-1
     host: auto
